//currency api constants
export const CURRENCY_LIST_REQUEST = "CURRENCY_LIST_REQUEST";
export const CURRENCY_LIST_SUCCESS = "CURRENCY_LIST_SUCCESS";
export const CURRENCY_LIST_FAIL = "CURRENCY_LIST_FAIL";

export const CURRENCY_DETAILS_REQUEST = "CURRENCY_DETAILS_REQUEST";
export const CURRENCY_DETAILS_SUCCESS = "CURRENCY_DETAILS_SUCCESS";
export const CURRENCY_DETAILS_FAIL = "CURRENCY_DETAILS_FAIL";

export const CURRENCY_DETAILS_BY_USER_REQUEST =
  "CURRENCY_DETAILS_BY_USER_REQUEST";
export const CURRENCY_DETAILS_BY_USER_SUCCESS =
  "CURRENCY_DETAILS_BY_USER_SUCCESS";
export const CURRENCY_DETAILS_BY_USER_FAIL = "CURRENCY_DETAILS_BY_USER_FAIL";

export const CURRENCY_REGISTER_REQUEST = "CURRENCY_REGISTER_REQUEST";
export const CURRENCY_REGISTER_SUCCESS = "CURRENCY_REGISTER_SUCCESS";
export const CURRENCY_REGISTER_FAIL = "CURRENCY_REGISTER_FAIL";

export const CURRENCY_SELL_REQUEST = "CURRENCY_SELL_REQUEST";
export const CURRENCY_SELL_SUCCESS = "CURRENCY_SELL_SUCCESS";
export const CURRENCY_SELL_FAIL = "CURRENCY_SELL_FAIL";

//user  constants
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";

export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAIL = "SEND_EMAIL_FAIL";
